In [1]:
from ipywidgets import Textarea
import io
import sys  # 使っていないが便宜上

if 'open' in globals():
    del open
if 'input' in globals():
    del input

original_open = open

class custom_open():
    def __init__(self):
        self.text = ''

    def __call__(self, file, *args, **kwargs):
        if file == 0:
            return io.StringIO(self.text)
        return original_open(file, *args, **kwargs)

    def updater(self, change):
        self.text = change["new"]

class custom_input():
    def __init__(self):
        self.__sio = io.StringIO('')
        self.shell = get_ipython()
        if self.shell.events.callbacks['pre_run_cell'] != []:
            self.shell.events.callbacks['pre_run_cell'] = []
        self.shell.events.register('pre_run_cell', self.pre_run_cell)

    def __call__(self):
        return self.__sio.readline().strip()

    def pre_run_cell(self, info):
        text = self.shell.user_ns.get('text_area', None).value
        self.__sio = io.StringIO(text)

open = custom_open()
input = custom_input()

text_area = Textarea()
text_area.observe(open.updater, names='value')
display(text_area)

Textarea(value='')

In [2]:
import numpy as np

H, W, N = map(int, input().split())
#array = [ [0] * W ] * H
array = np.zeros( (H, W), dtype=int)

for i in range(N):
    A, B = map(int, input().split())
    #print(A,B)
    array[A-1][B-1] = i+1
print(array)

while True:
    Flag = True
    old_array = array 
    print( ~np.all(array == 0, axis=1) ) 
    newarray = array[~np.all(array == 0, axis=1)]
    if newarray == array:
        Flag = False
    array = newarray 
    print( ~np.all(array == 0, axis=0) ) 
    newarray = array[:, ~np.all(array == 0, axis=0)]
    if newarray  == array:
        Flag = False
    array = newarray
   
    if Flag:
        break

for x in range(1, N+1):        
    i, j = np.where(array == x )
    print(int(i+1),int(j+1))
    
        
        

[[0 0 0 0 0]
 [0 0 0 0 2]
 [0 1 0 0 0]
 [0 0 0 0 0]]
[False  True  True False]
[False  True False False  True]
2 1
1 2


C:\Users\fumi_\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
C:\Users\fumi_\Anaconda3\lib\site-packages\ipykernel_launcher.py:23: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
